name: its12
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^2.0.6
  carousel_pro: ^1.0.0
  firebase_auth: ^0.18.4
  cloud_firestore: ^0.14.4
  google_sign_in: ^4.5.6
  firebase_database: ^4.4.0
  firebase_storage: ^5.2.0
  image_cropper: ^1.3.0
  flappy_search_bar: ^1.7.2
  flutter_staggered_grid_view: ^0.3.2
  shared_preferences: ^0.5.7+3
  fluttertoast: ^4.0.1
  characters: ^1.0.0
  image_picker: ^0.6.7+4
  url_launcher: ^5.5.0
  uuid: ^2.2.0
  firebase_core: ^0.5.3
  provider: ^4.3.2+1
  razorpay_flutter: ^1.2.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flare_splash_screen: ^2.0.1+2
  google_fonts:
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Products/cakes1.jpg
    - assets/Products/cakes2.jpg
    - assets/Products/pillow.jpg
    - assets/Products/flowerbouquet.jpg
    - assets/Products/silkoreo.jpg
    - assets/Products/tshirt.jpg
    - assets/New File 2.flr
    - assets/loadscreen.flr
    - assets/its12.jpg
    - assets/glogo.png
    - assets/new.png
    - assets/images/bouquets.png
    - assets/images/cakes.png
    - assets/images/gifts.png
    - assets/images/teddys.png
    - assets/images/watches.png
    - assets/jns2.jpg
    - assets/images/gift.jpg
    - assets/images/us.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
          style: italic
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
